GET http://localhost:4000/user-api/users

### read user by object id
GET http://localhost:4000/user-api/users/697dbc9f69e82d017c90a434


### create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"lucky",
    "password":"12345",
    "age":20
}

### update user
PUT http://localhost:4000/user-api/users/697dbc9f69e82d017c90a434
Content-Type: application/json

{
    "username":"candy",
    "password":"45670",
    "age":20

}
### Delete user
DELETE http://localhost:4000/user-api/users/697dbc9f69e82d017c90a434

###
GET http://localhost:4000/product-api/products

### Create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid":"34567",
    "productName":"facewash",
    "price":"500"
}

### Read product by object id
GET http://localhost:4000/product-api/products/697dd074d508d01acadb5497


### update product
PUT http://localhost:4000/product-api/products/697dd074d508d01acadb5497

{
   "pid":"34867",
    "productName":"hairdyer",
    "price":"800" 
}